//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkr_WPF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocsdbContext : DbContext
    {
        public DocsdbContext()
            : base("name=DocsdbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<project_has_employees> project_has_employees { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<stage> stages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<task_has_employees> task_has_employees { get; set; }
        public virtual DbSet<task_status> task_status { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_info> users_info { get; set; }
        public virtual DbSet<phone> phones { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<documents_status> documents_status { get; set; }
        public virtual DbSet<edit> edits { get; set; }
        public virtual DbSet<project_has_document> project_has_document { get; set; }
    }
}
