//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkr_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public document()
        {
            this.edits = new HashSet<edit>();
            this.project_has_document = new HashSet<project_has_document>();
        }
    
        public System.Guid uniqIdent { get; set; }
        public byte[] document_file { get; set; }
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string name { get; set; }
        public int user_info_id { get; set; }
        public int status_id { get; set; }
    
        public virtual documents_status documents_status { get; set; }
        public virtual users_info users_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edit> edits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_has_document> project_has_document { get; set; }
    }
}
