//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkr_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public int send_user_id { get; set; }
        public System.DateTime date { get; set; }
        public string text { get; set; }
        public int edit_id { get; set; }
    
        public virtual edit edit { get; set; }
        public virtual users_info users_info { get; set; }
    }
}
