//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkr_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_has_employees
    {
        public int id { get; set; }
        public int user_info_id { get; set; }
        public int task_id { get; set; }
    
        public virtual task task { get; set; }
        public virtual users_info users_info { get; set; }
    }
}
